### ISSUE TITLE
重复调用出现 Service Not Found

### ISSUE THREAD

**Issue by biezhi** [junicorn/mrpc#2]
mrpc第二次 或第三次调用 就会出现handler被回收的情况导致调用失败

```java
ERROR com.kongzhong.mrpc.client.cluster.ha.FailOverHaStrategy [qtp477831493-17] [7861920117042501607|1497874809616] #ELK#  com.kongzhong.mrpc.exception.RpcException: Service [com.kongzhong.finance.licai.tradeservice.api.service.InvestOrderService] not found.
	at com.kongzhong.mrpc.client.cluster.loadblance.SimpleLoadBalance.getInvoker(SimpleLoadBalance.java:40)
	at com.kongzhong.mrpc.client.cluster.ha.FailOverHaStrategy.call(FailOverHaStrategy.java:31)
	at com.kongzhong.mrpc.client.proxy.SimpleClientProxy.handleInvocation(SimpleClientProxy.java:39)
```

**Comment by biezhi** [comment]
fixed https://github.com/junicorn/mrpc/commit/21bc9cb6205394dbc862c4b20512b5bde193bcf1
